name: msmtpd

services:
  msmtpd:
    image: crazymax/msmtpd
    container_name: msmtpd
    ports:
      - target: 2500
        published: 2500
        protocol: tcp
    environment:
      - "TZ=Europe/Paris"
      - "PUID=1500"
      - "PGID=1500"
      - "SMTP_DEFAULT_HOST=smtp.gmail.com"
      - "SMTP_DEFAULT_PORT=587"
      - "SMTP_DEFAULT_TLS=on"
      - "SMTP_DEFAULT_TLS_STARTTLS=on"
      - "SMTP_DEFAULT_TLS_CERTCHECK=on"
      - "SMTP_DEFAULT_AUTH=on"
      - "SMTP_DEFAULT_USER_FILE=/run/secrets/smtp_user"
      - "SMTP_DEFAULT_PASSWORD_FILE=/run/secrets/smtp_password"
      - "SMTP_DEFAULT_DOMAIN=localhost"
    secrets:
      - smtp_user
      - smtp_password
    restart: always

secrets:
  smtp_user:
    external: true
  smtp_password:
    external: true
